feat: ping-2829 integrations test for put topics/follow
BetterSocial/user-api pull request #521
Opened 2023-10-04 15:27 UTC by brm-stnd

integrations test for topics/follow

2023-10-05 01:52 UTC, n-permana approved these changes

2023-10-08 23:12 UTC, falhar commented
why sonarcloud is not running?

2023-10-09 02:12 UTC, fajarism requested changes

2023-10-09 02:12 UTC, fajarism commented on __tests__/api/topics/follow.test.js
Please add test to check isAuth middleware on each test suite.

2023-10-09 13:27 UTC, brm-stnd commented on __tests__/api/topics/follow.test.js
added

2023-10-10 11:43 UTC, fajarism approved these changes

2023-10-10 11:46 UTC, merged