Feat/ping 2850 put topic follow v2
BetterSocial/user-api pull request #522
Opened 2023-10-06 14:52 UTC by brm-stnd

integrations test for topics/follow-v2

2023-10-07 12:56 UTC, falhar approved these changes

2023-10-08 06:53 UTC, n-permana approved these changes

2023-10-09 02:15 UTC, fajarism requested changes
same comment as #521

2023-10-09 13:17 UTC, brm-stnd commented
> same comment as #521

added 👍

2023-10-10 11:44 UTC, fajarism approved these changes

2023-10-10 11:46 UTC, merged