feat: ping-3329 unfoll anon users
BetterSocial/user-api pull request #593
Opened 2023-11-27 03:53 UTC by brm-stnd

2023-11-28 08:56 UTC, fajarism requested changes

2023-11-28 08:56 UTC, fajarism commented on controllers/profiles/unfollowAnonnimousUser.js
> +const moment = require('moment');
Typo on file name 
should be `unfollowAnonymousUser` or should be `unfollowAnonUser` for short

2023-11-28 15:49 UTC, bastian-purrer reviewed
<img src="https://avatars.githubusercontent.com/in/347564?s=41" alt="Image description" width="20" height="20">   CodeRabbit

<details>
<summary>Commits</summary>
Files that changed from the base of the PR and between 8a13c03ce3023e2c468a3b248056b5c9ca526513 and aefb345297af5548a4c46580536c8646937716b4 commits.
</details>

<details>
<summary>Files selected (3)</summary>

* controllers/profiles/index.js (2)
* controllers/profiles/unfollowAnonUser.js (1)
* routes/profiles.js (1)
</details>





<details>
<summary>Files not summarized due to errors (3)</summary>

* routes/profiles.js (nothing obtained from openai)
* controllers/profiles/index.js (nothing obtained from openai)
* controllers/profiles/unfollowAnonUser.js (nothing obtained from openai)

</details>


<details>
<summary>Files not reviewed due to errors (3)</summary>

* controllers/profiles/index.js (no response)
* controllers/profiles/unfollowAnonUser.js (no response)
* routes/profiles.js (no response)

</details>


<details>
<summary>Review comments generated (0)</summary>

* Review: 0
* LGTM: 0

</details>

---

<details>
<summary>Tips</summary>

### Chat with <img src="https://avatars.githubusercontent.com/in/347564?s=41&u=fad245b8b4c7254fe63dd4dcd4d662ace122757e&v=4" alt="Image description" width="20" height="20">  CodeRabbit Bot (`@coderabbitai`)
- Reply on review comments left by this bot to ask follow-up questions. A review comment is a comment on a diff or a file.
- Invite the bot into a review comment chain by tagging `@coderabbitai` in a reply.

### Code suggestions
- The bot may make code suggestions, but please review them carefully before committing since the line number ranges may be misaligned. 
- You can edit the comment made by the bot and manually tweak the suggestion if it is slightly off.

### Pausing incremental reviews
- Add `@coderabbitai: ignore` anywhere in the PR description to pause further reviews from the bot.

</details>

2023-11-29 10:13 UTC, fajarism approved these changes

2023-11-29 12:56 UTC, merged