feat: ping-3317 add attachments when send message
BetterSocial/user-api pull request #596
Opened 2023-11-28 04:40 UTC by n-permana

2023-11-28 04:41 UTC, bastian-purrer commented
<img src="https://avatars.githubusercontent.com/in/347564?s=41" alt="Image description" width="20" height="20">   CodeRabbit

<!-- This is an auto-generated comment: summarize review in progress by OSS CodeRabbit -->

Currently reviewing new changes in this PR...

<details>
<summary>Commits</summary>
Files that changed from the base of the PR and between f769068afd10f005121cf23ab52bc66b998c2aa3 and 4c030877e3f72c963c8d18f663bfd4ab54543a37 commits.
</details>

<details>
<summary>Files selected (2)</summary>

* controllers/chat/ChatController.js (3)
* controllers/chat/sendSignedMessage.js (3)
</details>




<!-- end of auto-generated comment: summarize review in progress by OSS CodeRabbit -->

---



<!-- This is an auto-generated comment: summarize by OSS CodeRabbit -->

2023-11-28 04:43 UTC, bastian-purrer reviewed
<img src="https://avatars.githubusercontent.com/in/347564?s=41" alt="Image description" width="20" height="20">   CodeRabbit

<details>
<summary>Commits</summary>
Files that changed from the base of the PR and between f769068afd10f005121cf23ab52bc66b998c2aa3 and 4c030877e3f72c963c8d18f663bfd4ab54543a37 commits.
</details>

<details>
<summary>Files selected (2)</summary>

* controllers/chat/ChatController.js (3)
* controllers/chat/sendSignedMessage.js (3)
</details>





<details>
<summary>Files not summarized due to errors (2)</summary>

* controllers/chat/sendSignedMessage.js (nothing obtained from openai)
* controllers/chat/ChatController.js (nothing obtained from openai)

</details>


<details>
<summary>Files not reviewed due to errors (2)</summary>

* controllers/chat/sendSignedMessage.js (no response)
* controllers/chat/ChatController.js (no response)

</details>


<details>
<summary>Review comments generated (0)</summary>

* Review: 0
* LGTM: 0

</details>

---

<details>
<summary>Tips</summary>

### Chat with <img src="https://avatars.githubusercontent.com/in/347564?s=41&u=fad245b8b4c7254fe63dd4dcd4d662ace122757e&v=4" alt="Image description" width="20" height="20">  CodeRabbit Bot (`@coderabbitai`)
- Reply on review comments left by this bot to ask follow-up questions. A review comment is a comment on a diff or a file.
- Invite the bot into a review comment chain by tagging `@coderabbitai` in a reply.

### Code suggestions
- The bot may make code suggestions, but please review them carefully before committing since the line number ranges may be misaligned. 
- You can edit the comment made by the bot and manually tweak the suggestion if it is slightly off.

### Pausing incremental reviews
- Add `@coderabbitai: ignore` anywhere in the PR description to pause further reviews from the bot.

</details>

2023-11-28 09:37 UTC, fajarism requested changes

2023-11-28 09:37 UTC, fajarism commented on controllers/chat/ChatController.js
>          ...req.body
Also please add feature flag for this sendMessage
We want to protect any existing endpoint to not be included to main when still in development

2023-11-28 13:07 UTC, n-permana commented on controllers/chat/ChatController.js
>          ...req.body
I think this is not necessary, because all messages have an 'attachments' field. We can check if this field is empty or not.

2023-11-29 10:15 UTC, fajarism approved these changes

2023-11-30 04:21 UTC, merged